spring:
  application:
    name: object-store

  datasource:
    url: jdbc:h2:file:./data/db
    username: sa
    password:

  h2:
    console:
      enabled: true

  sql:
    init:
      mode: always